### ISSUE TITLE
broken css + js src refs

### ISSUE THREAD

**Issue by nexus-uw** [bobmaerten/docker-wallabag#10]
Hi,

Am I currently running your docker image on a subdomain behind a nginx reverse proxy. Currently none of the styles on the page will load because their url source ref roots are set to localhost:[exposed docker container port]
![screen shot 2015-12-27 at 11 20 58 pm](https://cloud.githubusercontent.com/assets/3188890/12014105/853ab1f2-acf3-11e5-814b-86b848b5ced2.png)

**Comment by bobmaerten** [comment]
Wallabag extract itself this `localhost:8081` as `poche_url` in the code source (inc/poche/Tools.class.php:41).
The following sequence is use to detect host : 
```php
$host = (isset($_SERVER['HTTP_X_FORWARDED_HOST']) ? $_SERVER['HTTP_X_FORWARDED_HOST'] : (isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : $_SERVER['SERVER_NAME']));
```

So maybe you could just find a way to propagate `HTTP_X_FORWARDED_HOST` value in your nginx proxy config?

**Comment by nexus-uw** [comment]
thanks for the tip @bobmaerten,
adding the following to my server's location settings fixed my issue.
```
location / {
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header        X-Forwarded-Proto $scheme;
                proxy_set_header Host      $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://localhost:8080;
        }
````

**Comment by bobmaerten** [comment]
Glad you managed to make it run!

**Comment by bateria2x100** [comment]
I m running my docker on a Synology and no behind any proxy, but same problem, CSS ara not 
working. Any ideas please ?  ?


![quickstart wallabag 2018-01-27 08-22-23](https://user-images.githubusercontent.com/35531034/35469695-3c5c5a58-033b-11e8-9396-c34bc457fd7e.jpg)
