### ISSUE TITLE
Support wallabag 2.0

### ISSUE THREAD

**Issue by eliihen** [bobmaerten/docker-wallabag#11]
Hi,

Since you have the most downloaded and starred docker image for wallabag, I thought I might direct the question at you. Do you have any plans to support wallabag 2.0?

**Comment by bobmaerten** [comment]
Hi @esphen! No, I do not plan to, as it seems to have a Dockerfile in the wallabag's v2 repository. I think they might know better how to deal with their architecture.

**Comment by esphen** [comment]
Interesting! They do indeed have a `Dockerfile` and a `docker-compose.yml` in the main repository. Thanks, I'll have a look at that.
