### ISSUE TITLE
remove host key generation from dockerfile 

### ISSUE THREAD

**Issue by gabeos** [bobmaerten/docker-wallabag#6]
hey @bobmaerten, 
thanks for the nicely done and well documented container recipe. just noticed the following, and thought I'd ping you about it. 

relatively minor thing, but since hosting ones own Web data services is often about privacy, I believe the phusion 00_regenerate_host_keys.sh script should be left to the container boot, so that users who run the image from the docker registry rather than building it themselves have unique keys that wouldn't be susceptible to man-in-the-middle attacks. as is, one could use the key from the publicly available image to intercept communication with the docker container.

**Comment by bobmaerten** [comment]
Your absolutly right, I haven't thought about it back then.
