### ISSUE TITLE
Initial set-up/registration

### ISSUE THREAD

**Issue by gabeos** [bobmaerten/docker-wallabag#7]
I don't see it documented how to log-in initially once the container is up. I went in and modified config.inc.php by hand to temporarily allow user registration, but it'd be great if you could do this through environment variables or something. Or if there is a way, could you put it in the readme?

Also, you may consider generating a secure salt value in the init script, via `openssl rand -base64 32` or some other command. I know the salt value has to be persistent, so you'd have to write a lock file somewhere safe to remember that you've already generated it or something. your call though, it might make it more of a hassle, and lead to data loss if it's not done carefully or people don't understand how to use it. just a thought. 

thanks! Otherwise super easy.

**Comment by bobmaerten** [comment]
The default startup script provided links a sqlite database configured with a user/pass couple as wallabag/wallabag. But the passwd hash is generated with a bunch of variables (name+pass+salt if I remember correctly within wallabag's code) so why not think about moving it throught env vars, but wallabag's going to change very soon (2.x branch) and I don't want to spend to much time on this.

**Comment by gabeos** [comment]
Ah okay, yeah, that makes sense, I just didn't see the standard login documented anywhere, and figured i'd make a note of the other things i'd noticed setting it up.

Didn't know wallabag was coming up for a big release, very cool. looking forward to checking it out.
