### ISSUE TITLE
Change var/www/wallabag/db permissions

### ISSUE THREAD

**Issue by hucal** [bobmaerten/docker-wallabag#8]
Hello, I've run the image and found it very helpful. Unfortunately, I had to change the permissions of the ```db/``` directory to get the server working. This was prompted by the server's error message ``` An error occured: "db" directory must be writeable for your web server user! ```

Temporary fix:
```bash
sudo docker exec -it (CONTAINER ID HERE) /bin/bash
cd /var/www/wallabag
sudo chown -R www-data:www-data db
```

I'm not too experienced with Docker, but I'm guessing the Dockerfile needs adjusting. It could also be a wallabag issue.

**Comment by bobmaerten** [comment]
You're right there's a flaw with the image self-setup. That's why there is the [docker-wallabag script](https://github.com/bobmaerten/docker-wallabag/blob/master/scripts/wallabag-docker) in this repo to start/stop/restart the container (which does exactly what you did for the db folder).
